// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthJwtLoginData,
  AuthJwtLoginErrors,
  AuthJwtLoginResponses,
  AuthJwtLogoutData,
  AuthJwtLogoutErrors,
  AuthJwtLogoutResponses,
  ConvertGuestData,
  ConvertGuestErrors,
  ConvertGuestResponses,
  CreateGuestData,
  CreateGuestResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  RegisterRegisterData,
  RegisterRegisterErrors,
  RegisterRegisterResponses,
  ResetForgotPasswordData,
  ResetForgotPasswordErrors,
  ResetForgotPasswordResponses,
  ResetResetPasswordData,
  ResetResetPasswordErrors,
  ResetResetPasswordResponses,
  UsersCurrentUserData,
  UsersCurrentUserErrors,
  UsersCurrentUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserResponses,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserErrors,
  UsersPatchCurrentUserResponses,
  UsersPatchUserData,
  UsersPatchUserErrors,
  UsersPatchUserResponses,
  UsersUserData,
  UsersUserErrors,
  UsersUserResponses,
  VerifyRequestTokenData,
  VerifyRequestTokenErrors,
  VerifyRequestTokenResponses,
  VerifyVerifyData,
  VerifyVerifyErrors,
  VerifyVerifyResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Guest
 *
 * Create an ephemeral guest account and return a short-lived Bearer JWT.
 *
 * The generated email (guest-<uuid>@guest.example) is intentionally unusable
 * for login.  The hashed password is a random UUID — also not usable.
 * is_guest=True marks the account for conversion.
 *
 * The JWT lifetime is controlled by GUEST_TOKEN_LIFETIME_SECONDS (default 72h).
 */
export const createGuest = <ThrowOnError extends boolean = false>(
  options?: Options<CreateGuestData, ThrowOnError>,
) =>
  (options?.client ?? client).post<CreateGuestResponses, unknown, ThrowOnError>(
    { url: "/auth/guest", ...options },
  );

/**
 * Convert Guest
 *
 * Convert a guest account to a permanent account.
 *
 * The caller must present a valid guest Bearer JWT.  The SAME user row is
 * updated in-place (email + hashed_password + is_guest=False) so the user id
 * is preserved and any ContextRocket-side session context survives intact.
 *
 * Raises 400 if the caller is already a permanent (non-guest) account.
 * Raises 400 if the requested email is already taken by another user.
 */
export const convertGuest = <ThrowOnError extends boolean = false>(
  options: Options<ConvertGuestData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ConvertGuestResponses,
    ConvertGuestErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/convert",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Users
 *
 * Return a paginated list of users for operator review.
 *
 * Only accessible to superusers.  Returns id, email, is_guest, and
 * is_active.  No sensitive fields (hashed_password, etc.) are exposed.
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/operator/users",
    ...options,
  });
