/**
 * Locale message registry -- GENERATED by scripts/generate-i18n-registry.mjs.
 * Do not edit by hand; add a <locale>.ts barrel in i18n/messages/ and
 * re-run the generator.
 *
 * This file is client-safe: it carries only locale metadata, never message
 * trees.
 */

export const SUPPORTED_LOCALES = ["de", "en", "es"] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

/** Conventional translated labels in the shared locale slice. */
export const LOCALE_LABEL_PATHS: Record<SupportedLocale, string> = {
  de: "locale.labelGerman",
  en: "locale.labelEnglish",
  es: "locale.labelSpanish",
};
