/**
 * Server-only locale registration -- GENERATED by
 * scripts/generate-i18n-registry.mjs.
 *
 * English is bundled eagerly (the fallback tree and the source of the `Path`
 * type). Non-en trees are loaded + registered LAZILY via explicit dynamic
 * import, so an inactive language is never compiled into the server graph -- a
 * narrowed dev build (`NEXT_PUBLIC_CR_UI_LOCALES`) compiles only the locales it
 * actually renders. This module must NEVER appear in the client bundle; the
 * `import "server-only"` guard enforces that.
 *
 * `getServerLocaleTree` (async) lets the [locale] layout register + pass the
 * active locale's tree to LocaleProvider (RSC payload injection). The layout
 * awaits it before rendering children, so every server `t()` under it resolves
 * from the registered active-locale tree.
 */

import "server-only";
import { en } from "./en";
import { registerLocaleMessages } from "../keys";
import type { SupportedLocale } from "./registry";

// English is always present: register it once at module init (server-side).
registerLocaleMessages("en", en as unknown as Record<string, unknown>);

// Non-en trees: explicit per-locale dynamic import (NOT a computed specifier,
// which would build a directory request-context) so each is its own chunk and
// only compiled when actually requested.
const NON_EN_LOADERS: Partial<
  Record<SupportedLocale, () => Promise<Record<string, unknown>>>
> = {
  de: async () =>
    (await import("./de")).de as unknown as Record<string, unknown>,
  es: async () =>
    (await import("./es")).es as unknown as Record<string, unknown>,
};

const _registered = new Set<SupportedLocale>(["en"]);

/**
 * Ensure the given locale's tree is registered in the server-side keys.ts
 * registry, and return it for RSC-payload injection. Returns null for en (the
 * English tree is always bundled client-side as the fallback).
 */
export async function getServerLocaleTree(
  locale: SupportedLocale,
): Promise<Record<string, unknown> | null> {
  if (locale === "en") return null;
  // Cast: in a single-locale (en-only) build `locale` narrows to `never` after
  // the guard above, which would make this index access non-callable.
  const load = NON_EN_LOADERS[locale as SupportedLocale];
  if (!load) return null;
  const tree = await load();
  if (!_registered.has(locale)) {
    registerLocaleMessages(locale, tree);
    _registered.add(locale);
  }
  return tree;
}
