/**
 * Server-only locale registration -- GENERATED by
 * scripts/generate-i18n-registry.mjs.
 *
 * Keep this file generated: the complete set of locale trees is discovered
 * from i18n/messages/<locale>.ts so forks can add locales without changing
 * starter-owned runtime wiring.
 */

import "server-only";

import { de } from "./de";
import { en } from "./en";
import { es } from "./es";
import { registerLocaleMessages } from "../keys";
import type { SupportedLocale } from "./registry";

registerLocaleMessages("de", de as unknown as Record<string, unknown>);
registerLocaleMessages("en", en as unknown as Record<string, unknown>);
registerLocaleMessages("es", es as unknown as Record<string, unknown>);

export function getServerLocaleTree(
  locale: SupportedLocale,
): Record<string, unknown> | null {
  if (locale === "en") return null;
  const trees: Partial<Record<SupportedLocale, Record<string, unknown>>> = {
    "de": de as unknown as Record<string, unknown>,
    "es": es as unknown as Record<string, unknown>,
  };
  return trees[locale] ?? null;
}
