/**
 * i18n test fixtures -- GENERATED by scripts/generate-i18n-registry.mjs.
 *
 * Keeping these imports generated lets the shared tests exercise every
 * configured locale while allowing a fork to remove unused locale bundles.
 */

import { de } from "./de";
import { sharedDe } from "./shared/de";
import { appDe } from "./app/de";
import { siteDe } from "./site/de";
import { en } from "./en";
import { sharedEn } from "./shared/en";
import { appEn } from "./app/en";
import { siteEn } from "./site/en";
import { es } from "./es";
import { sharedEs } from "./shared/es";
import { appEs } from "./app/es";
import { siteEs } from "./site/es";

export const LOCALE_MESSAGE_TREES = {
  "de": de,
  "en": en,
  "es": es,
} as const;

export const LOCALE_MESSAGE_SLICES = {
  "de": {
    merged: de,
    shared: sharedDe,
    app: appDe,
    site: siteDe,
  },
  "en": {
    merged: en,
    shared: sharedEn,
    app: appEn,
    site: siteEn,
  },
  "es": {
    merged: es,
    shared: sharedEs,
    app: appEs,
    site: siteEs,
  },
} as const;
