/**
 * GENERATED by scripts/generate-i18n-registry.mjs.
 *
 * Add a message surface under modules/<surface>/de.ts; do not edit
 * this barrel by hand. The source module remains fork-owned when applicable.
 */

import { chatDe } from "./chat/de";
import { devDe } from "./dev/de";
import { embedDe } from "./embed/de";

export const modulesDe = {
  ...chatDe,
  ...devDe,
  ...embedDe,
} as const;
