/**
 * GENERATED by scripts/generate-i18n-registry.mjs.
 *
 * Add a message surface under modules/<surface>/en.ts; do not edit
 * this barrel by hand. The source module remains fork-owned when applicable.
 */

import { chatEn } from "./chat/en";
import { devEn } from "./dev/en";
import { embedEn } from "./embed/en";

export const modulesEn = {
  ...chatEn,
  ...devEn,
  ...embedEn,
} as const;
