/**
 * GENERATED by scripts/generate-i18n-registry.mjs.
 *
 * Add a message surface under modules/<surface>/es.ts; do not edit
 * this barrel by hand. The source module remains fork-owned when applicable.
 */

import { chatEs } from "./chat/es";
import { devEs } from "./dev/es";
import { embedEs } from "./embed/es";

export const modulesEs = {
  ...chatEs,
  ...devEs,
  ...embedEs,
} as const;
