/**
 * Client locale loaders -- GENERATED by
 * scripts/generate-i18n-registry.mjs.
 *
 * This is intentionally an explicit import map. A computed import over the
 * messages directory can pull server-only registration into the client
 * bundle.
 */

import type { SupportedLocale } from "./messages/registry";

export type LocaleLoader = () => Promise<Record<string, unknown>>;

export const CLIENT_LOCALE_LOADERS: Partial<
  Record<SupportedLocale, LocaleLoader>
> = {
  "de": () => import("./messages/de").then((m) => m.de as Record<string, unknown>),
  "es": () => import("./messages/es").then((m) => m.es as Record<string, unknown>),
};
