/**
 * Site message slices -- GENERATED by scripts/generate-i18n-registry.mjs.
 *
 * The site-content adapter imports this map instead of hard-coding a fixed
 * set of languages. A single-language fork therefore ships only its own
 * site message bundle.
 */

import { siteDe } from "./messages/site/de";
import { siteEn } from "./messages/site/en";
import { siteEs } from "./messages/site/es";

export const SITE_MESSAGE_SLICES: Record<string, Record<string, unknown>> = {
  "de": siteDe as unknown as Record<string, unknown>,
  "en": siteEn as unknown as Record<string, unknown>,
  "es": siteEs as unknown as Record<string, unknown>,
};
